### ISSUE TITLE
Content type for raw API should match the `format` field

### ISSUE THREAD

**Issue by omern1** [muhammadmuzzammil1998/BingHomepageAPI#2]
`https://cdn.muzzammil.xyz/bing/bing.php?format=json&cc=US` returns the content type as "text/html". The content type should be "application/json".

**Comment by muhammadmuzzammil1998** [comment]
Hopefully, the issue is fixed now. Thanks for bringing it into my notice.

**Comment by omern1** [comment]
It's fixed, thanks.
